### PR TITLE
Added 4 devices, fixed alarm type for water leak sensors

### PR DESCRIPTION
**Pull request by hallard**
Added

- MOES _TZ3000_w8jwkczz (3 Gangs wall remote)
- MOES _TZ3000_xabckq1v (4 Gangs wall remote)
- Added DIY smart switch _TZ3000_hktqahrq
- Blitzwolf _TZ3000_eit7p838  TS0207 Water Leak

### CODE REVIEW

**Comment by JohanBendz** [comment]
Hi, this looks good :) I will merge it once I have updated github with the changes I have made localy. Just have to clean up some code first :)

And yeah.. TS0001 can't possibly be anything else than a 1 gang unit... or Tuya would have totally destroyed their naming strategy ;) :)

**Comment by hallard** [comment]
yeah was my first though after PR why I added 2 gangs (because 2 switches) if TS0001 :-)

I noticed also a typo in waterleak I added blitwolf. It works but it's labeled (when click on device in homey) as Alarm Contact instead of Alarm Water (and icon is contact not water) so I guess should be added as new device?

**Comment by hallard** [comment]
may be just replace in `capabilities`
`alarm_contact` by `alarm_water`, that's what it's done in aquara xiaomi zigbee :-)

**Comment by hallard** [comment]
@JohanBendz ok, tested and fixed water leak sensor alarm

**Comment by JohanBendz** [comment]
@hallard I will have to make some changes, when one wants to change a device from one capability to another one have to add the new capability and set the old one as deprecated, else the device will become broken for those that have it installed already. (contact to water)

**Comment by hallard** [comment]
> @hallard I will have to make some changes, when one wants to change a device from one capability to another one have to add the new capability and set the old one as deprecated, else the device will become broken for those that have it installed already. (contact to water)

Correct, missed that old compatibility one.

**Comment by JohanBendz** [comment]
Hi @hallard, sorry for the long wait.. been really busy. :( 
I have now added your code to the app and fixed what needed fixing, will be included in next release.
Thanks again for the help! :)

**Pull request closed without merging**
