### PR TITLE
Update for button + 2 new devices

### PR DESCRIPTION
**Pull request by nuker1991**
On my homey early 2023 with the switch _TZ3000_wkai4ga5 i dont require a debounce.

### CODE REVIEW

**Comment by nuker1991** [comment]
Added the _TZ3000_ja5osu5g MOES ERS-10TZBVB-AA

**Comment by nuker1991** [comment]
Added and tested soil sensor _TZE200_myd45weu

**Comment by robgBY** [comment]
Hi @nuker1991 ,

Would this pull request solve the issue that the _TZ3000_wkai4ga5 is currently not working?

**Comment by nuker1991** [comment]
> Hi @nuker1991 ,
> 
> Would this pull request solve the issue that the _TZ3000_wkai4ga5 is currently not working?

That should be fixed in commit 0c56886, Johan already merged that one, maybe he didnt publish it yet.
i removed the debounce at commit 4d0249c in this pull request.

Are you running the test version with your homey ?
https://homey.app/en-us/app/com.tuya.zigbee/Tuya-Zigbee/test/

PS: he didnt publish it yet it seems :)

**Comment by JohanBendz** [comment]
Hi @nuker1991, nice PR.
Do this 1 button have two clusters? 6 and 8 ? Can you share an interview? I have only seen one in the interviews I have seen before. Thanks for the debounce fix, as I don't have it I have to rely on others to find what is and is not working :)

**Comment by nuker1991** [comment]
> Hi @nuker1991, nice PR. Do this 1 button have two clusters? 6 and 8 ? Can you share an interview? I have only seen one in the interviews I have seen before. Thanks for the debounce fix, as I don't have it I have to rely on others to find what is and is not working :)

I still need to look i to it if it can be simplified, with my initial testing when pressing in a unidentified time out it seems to change clusters.

**Comment by WJGvdVelden** [comment]
Hi, @nuker1991 and @JohanBendz . I recently installed the _TZ3000_ja5osu5g 1-button. And with me it didn't work correctly.
The cluster-ID is 6, but the one click and double-clicks are reversed. Also the value of frame[2] can be 253. When running the debug I get the log below.
In essence it looks as if this device has more in common with the smart_remote_1_button and not the added version smart_remote_1_button_2.

_//1 click
2024-11-19T19:09:05.423Z zigbee-clusters:cluster ep: 1, cl: onOff (6) read attributes result { attributes: <Buffer 00 00 00 10 01> }
2024-11-19T19:09:05.424Z [log] [ManagerDrivers] [Driver:plug] [Device:3b973d6c-af9e-4679-9952-82bf92e0598d] handle report (cluster: onOff, capability: onoff), parsed payload: true
2024-11-19T19:09:05.425Z [log] [ManagerDrivers] [Driver:plug] [Device:3b973d6c-af9e-4679-9952-82bf92e0598d] get → onoff → read attribute (cluster: onOff, attributeId: onOff, endpoint: 1) → parsed result true
2024-11-19T19:09:10.912Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] endpointId: 1 , clusterId: 6 , frame: <Buffer 11 6b fd 00> , meta: { transId: 0, linkQuality: 31, dstEndpoint: 1, timestamp: 2105062 }
2024-11-19T19:09:10.913Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame JSON data: { type: 'Buffer', data: [ 17, 107, 253, 0 ] }
2024-11-19T19:09:10.914Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [1]:  107
2024-11-19T19:09:10.914Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [2]:  253
2024-11-19T19:09:10.915Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [3]:  0
2024-11-19T19:09:10.946Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Triggered 1 button Smart Remote, action=twoClicks
2024-11-19T19:09:11.162Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] endpointId: 1 , clusterId: 6 , frame: <Buffer 11 6c 02> , meta: { transId: 0, linkQuality: 31, dstEndpoint: 1, timestamp: 2105842 }
2024-11-19T19:09:11.162Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame JSON data: { type: 'Buffer', data: [ 17, 108, 2 ] }
2024-11-19T19:09:11.163Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [1]:  108
2024-11-19T19:09:11.164Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [2]:  2
2024-11-19T19:09:11.164Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [3]:  undefined
2024-11-19T19:09:11.174Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Triggered 1 button Smart Remote, action=twoClicks

//2-clicks
2024-11-19T19:09:15.234Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] endpointId: 1 , clusterId: 6 , frame: <Buffer 11 6d fd 01> , meta: { transId: 0, linkQuality: 28, dstEndpoint: 1, timestamp: 2118561 }
2024-11-19T19:09:15.238Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame JSON data: { type: 'Buffer', data: [ 17, 109, 253, 1 ] }
2024-11-19T19:09:15.239Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [1]:  109
2024-11-19T19:09:15.240Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [2]:  253
2024-11-19T19:09:15.240Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [3]:  1
2024-11-19T19:09:15.253Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Triggered 1 button Smart Remote, action=twoClicks
2024-11-19T19:09:15.537Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] endpointId: 1 , clusterId: 6 , frame: <Buffer 11 6e 01> , meta: { transId: 0, linkQuality: 31, dstEndpoint: 1, timestamp: 2119335 }
2024-11-19T19:09:15.538Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame JSON data: { type: 'Buffer', data: [ 17, 110, 1 ] }
2024-11-19T19:09:15.539Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [1]:  110
2024-11-19T19:09:15.540Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [2]:  1
2024-11-19T19:09:15.540Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Frame [3]:  undefined
2024-11-19T19:09:15.558Z [log] [ManagerDrivers] [Driver:wall_switch_1_gang] [Device:7ef1dd6f-0f02-4af9-97d0-e0d6b675ae37] set onoff → false (cluster: onOff, endpoint: 1)
2024-11-19T19:09:15.563Z [log] [ManagerDrivers] [Driver:smart_remote_1_button_2] [Device:1f141fa0-e180-4fa7-b117-add4e078305e] Triggered 1 button Smart Remote, action=oneClick
2024-11-19T19:09:15.559Z zigbee-clusters:cluster ep: 1, cl: onOff (6) send frame ZCLStandardHeader {
  frameControl: [ 'clusterSpecific' ],
  data: <Buffer >,
  cmdId: 0,
  trxSequenceNumber: 2
}
2024-11-19T19:09:15.902Z zigbee-clusters:cluster ep: 1, cl: onOff (6) received frame defaultResponse onOff.defaultResponse { cmdId: 0, status: 'SUCCESS' }
2024-11-19T19:09:15.922Z zigbee-clusters:cluster ep: 1, cl: onOff (6) received frame reportAttributes onOff.reportAttributes { attributes: <Buffer 00 00 10 00> }
2024-11-19T19:09:15.934Z [log] [ManagerDrivers] [Driver:wall_switch_1_gang] [Device:7ef1dd6f-0f02-4af9-97d0-e0d6b675ae37] handle report (cluster: onOff, capability: onoff), parsed payload: false
202_

**Comment by JohanBendz** [comment]
Hi @WJGvdVelden, please create a new issue with the status Bug regarding this.

**Pull request merged**
