### PR TITLE
Improved curtain_modul driver

### PR DESCRIPTION
**Pull request by mhaid**
Added support for essential settings, like drive time or motor reversal.

### CODE REVIEW

**Comment by jepke** [comment]
Tested it with ones i have #510 no issues. Mine have upper and lower limit setting, so far havent been able to figure out how to code settings yet.

**Comment by tfoldi** [comment]
I implemented somewhat similar stuff for myself to support `_TZ3000_j1xl73iw`. Any chances that this PR will be merged?

**Comment by pwvandeursen** [comment]
@tfoldi , @JohanBendz , was #362 merged? looking forwards to seeing this one being used at home in combination with the new calibration option.

Thanks!!

**Comment by JohanBendz** [comment]
Thanks for the PR @mhaid, merged and will be in next update.

**Pull request merged**
