### PR TITLE
Added radar sensor support for TS0601/_TZE204_qasjif9e

### PR DESCRIPTION
**Pull request by pbruining**

### CODE REVIEW

**Comment by JohanBendz** [comment]
Already added to next release.

**Comment by pbruining** [comment]
Thanks!

**Comment by Roobbbiiiinnnnn** [comment]
Unfortunately, it still doesn't work. I get the error "something went wrong when the device was added, please try again"
Screenshot_20240205-162135

**Comment by pieter-hydraloop** [comment]
That's weird, it's hanging at my ceiling and I'm using it every day. Are you sure it's the same device?

**Comment by Roobbbiiiinnnnn** [comment]
> That's weird, it's hanging at my ceiling and I'm using it every day. Are you sure it's the same device?

Can you give me a link to the one you've got?

**Comment by JohanBendz** [comment]
@Roobbbiiiinnnnn, that's a Homey pairing issue and not an issue with the app. Try pressing the "pair-button" on the device every other second while pairing it with Homey.

**Comment by Roobbbiiiinnnnn** [comment]
That's really strange. I was able to add it as a generic device before the new updates of the app!


________________________________
Från: Johan Bendz ***@***.***>
Skickat: tisdag, februari 6, 2024 11:34:24 em
Till: JohanBendz/com.tuya.zigbee ***@***.***>
Kopia: Roobbbiiiinnnnn ***@***.***>; Mention ***@***.***>
Ämne: Re: [JohanBendz/com.tuya.zigbee] Added radar sensor support for TS0601/_TZE204_qasjif9e (PR #652)


@Roobbbiiiinnnnn<https://github.com/Roobbbiiiinnnnn>, that's a Homey pairing issue and not an issue with the app. Try pressing the "pair-button" on the device every other second while pairing it with Homey.

**Pull request closed without merging**
