### PR TITLE
Add support for Tuya curtain motors

### PR DESCRIPTION
**Pull request by BertvanHoekelen**
Hey @JohanBendz, thanks for the well written app 💪🏼.

I have added support for the [Tuya curtain motors](https://nl.aliexpress.com/item/1005002551866480.html). I got the icon from the [homey-vectors](https://github.com/athombv/homey-vectors-public/blob/master/com.xiaomi-mi-zigbee/drivers/curtain/assets/icon.svg) repo as this motor looks identical to the aqara motor. I got the list of manufacturer names from the [Zigbee2MQTT](https://github.com/M10TrungPhan/Zigbee2MQTT/blob/1657c0869b24329a9afff4a65bd0ecadc9ad69c1/zigbee2mqtt-master/zigbee-herdsman-converters/devices/tuya.js#L472-L483) repo.

You might be wondering why I didn't use the attributes in TuyaSpecificCluster. These are only set when the received command is global and not [cluster specific](https://github.com/athombv/node-zigbee-clusters/blob/master/lib/Cluster.js#L694-L700). Took me some time to figure this out but managed to get it working 😃 

I also created an abstract Tuya specific device as I reused some methods from christmas_lights and wanted to avoid code duplication.

### CODE REVIEW

**Comment by JohanBendz** [comment]
Hi @BertvanHoekelen, thanks! 😃 

Nice PR, looks great from what I can see so far. I'll have a look at it asap. 

As I don't have this device I will trust you to validate the functionality. 😄

**Comment by BertvanHoekelen** [comment]
Thanks! I have tested it with multiple motors and everything works as expected 💪🏼  I don't have the christmas lights but the only thing I changed there is using the abstract class.

**Comment by github-acedom** [comment]
I've just tested this with my curtain motor by adding `_TZE200_pw7mji0l` to the list of manufacturerName

Purchased from https://www.ozsmartthings.com.au/collections/smart-blinds/products/zigbee-smart-blind-motor

Seems to work well.

**Comment by BertvanHoekelen** [comment]
@github-acedom Awesome! I have added it to the current PR.

**Pull request closed without merging**
