### PR TITLE
Add new temp/humidity sensor TZE204_yjjdcqsq, incompatible with TZE200 driver

### PR DESCRIPTION
**Pull request by slicke**
Adds driver for TS0601 / _TZE204_yjjdcqsq. I found that it its very different from the current models of temp/humidifiers and based a new driver on the Siren+temp/humidifier base (same chip generation) + figured out the correct dp:s

### CODE REVIEW

**Comment by slicke** [comment]
Note that it takes like 20-30 mins after installing the device for it to actually send data, so it will show up as "-- degrees" for the first half hour

**Comment by JohanBendz** [comment]
Hi @slicke, nice PR.
I notice inconsistency in how the large and small image looks and how the icon and learn svg files look. Something you can fix?

Oh, one more thing.. whats this in the json file?
"capabilitiesOptions": {
    "onoff": {
      "greyout": false
    }
  },

**Comment by slicke** [comment]
Sure! Ill check it out. I just added _TZE200_vvmbj46n as well.

**Comment by slicke** [comment]
Hi again :) Hopefully the latest changes will do it @JohanBendz :)

**Comment by JohanBendz** [comment]
Thanks @slicke, all good now! :)

**Comment by JohanBendz** [comment]
Hi @slicke, I was sloppy checking your code... in device.js you have code using fetch.. should not be in the production environment. I will remove it and add standard error logging.

**Pull request merged**
