### PR TITLE
Added AVATTO 1 gang dimmer module _TZE204_5cuocqty / TS0601

### PR DESCRIPTION
**Pull request by galaxyprof**
Added and succesfully tested this device. Also requested by someone else as a new device request #944

### CODE REVIEW

**Comment by JohanBendz** [comment]
Added to next release, thanks for info.

**Comment by janharmveenstra** [comment]
The Avatto dimmer switch does not been reqonized by homey when connection. would be nice for a fix

**Comment by galaxyprof** [comment]
@janharmveenstra 
I can reconfirm that my device is functioning correctly with this device id. Make sure to check your device id. Avatto has a range of modules which may have different id's. Each will have to be added individually.

**Comment by janharmveenstra** [comment]
@galaxyprof i've added the device, its ''_TZE204_5cuocqty'' but homey keeps saying ''this device doesnt support on/off fuction''. but i believe your word. i think i miss something

**Comment by galaxyprof** [comment]
@janharmveenstra
My module is a (yellow coloured) 1-gang dimmer module. Maybe you added it as a generic Zigbee device?
I added the module from within the Tuya Zigbee app. There are multiple choices there, try them all.
If unsuccessful we can compare the interviews.

**Pull request closed without merging**
