### PR TITLE
_TZE204_sxm7l9xa fixes, please cherry pick only ac206c8 and a2ef0ed

### PR DESCRIPTION
**Pull request by shaarkys**
Hi @JohanBendz , this is pull request for [_TZE204_sxm7l9xa) fixes] but please cherry pick only : 

https://github.com/JohanBendz/com.tuya.zigbee/commit/ac206c8c460c6d558901b492108f6f4784325663 (_TZE204_sxm7l9xa fixes)
and
https://github.com/JohanBendz/com.tuya.zigbee/commit/118a13b746da94fe12b5583d917e13d5592e90b5 (_TZE204_sxm7l9xa fixes)
and
 [a2ef0ed](https://github.com/JohanBendz/com.tuya.zigbee/pull/743/commits/a2ef0ed19a28a9e46f17c073247d9a0788400a7d), ( Fix for measure_battery on Smart Garden Irrigation Controller)

as in parallel I'm testing ([Experimental - update to latest homey-zigbeedriver and zigbee-cluste](https://github.com/JohanBendz/com.tuya.zigbee/commit/0f3ca87a64d9eb36f7b5dfba0ec23a69ca484a31)) but I'm unable to submit it without.

I'm sure you are able to find a way ;-)

### CODE REVIEW

**Comment by JohanBendz** [comment]
Thanks @shaarkys, I'll give it a go during the week.

**Comment by shaarkys** [comment]
Thank you, for the irrigation controller, seems the battery level gets not updated, seems Tuya send it in the DP 101, checking

**Comment by shaarkys** [comment]
The radar sensors keeps working fine

**Comment by shaarkys** [comment]
Modified also device.js for _TZ3210_eymunffl for battery monitoring. However based on https://www.zigbee2mqtt.io/devices/R7060.html, it can take up to 24 hours to get battery reflected. But you will see if the code is right or not, so I trust your experience. ;-)

**Comment by shaarkys** [comment]
So this is working code for : 

- _TZ3210_eymunffl (Smart Garden Irrigation Controller ) fixed to include battery monitoring and reflect back state, when controlled by the device
- added new doorwindowsensor_4 for zbeacon / DS01 including battery monitoring (AAA batteries)
- extended doorwindowsensor , added _TZ3000_1bwpjvlz including battery monitoring  (CR2032)
- Radar Sensor ZY-M100-S/L (_TZE204_sxm7l9xa) added as radar_sensor_2, fixed distance/occupancy state
- upgraded  homey-zigbeedriver and zigbee-cluster to the latest  and fixed arrays definitions

It works for me, not GitHUB expect, sorry for mess but was working on those last few days, hopefully it's good for something @JohanBendz

**Comment by JohanBendz** [comment]
Thanks @shaarkys, I have picked stuff and added to the app. Some things are yet to fix but I have them on my radar.

**Comment by shaarkys** [comment]
Hi @JohanBendz , thank you, prior switching back to your much matured code, I see you did not implement target_distance_changed trigger for ceiling radar sensor ZY-M100-S/L, is that automatically created trigger please ? (just you know prior me repairing those devices and finding it out myself, it's always a pain with Zigbee)

Using it to differentiate when movement is detected behind wall ;-)

Thank you.

**Comment by JohanBendz** [comment]
Hi @shaarkys, I have the code ready for next update. (hence "on my radar" :) )

**Pull request closed without merging**
