### PR TITLE
Added 4 channel relay board and smart metering plug

### PR DESCRIPTION
**Pull request by melkuier**
4 channel relay board:
ProductID: TS0004
Manufacturer: _TZ3000_hdlpifbk

Smart metering plug:
ProductID: TS011F
Manufacturer: _TZ3000_cphmq0q7

### CODE REVIEW

**Comment by JohanBendz** [comment]
Hi @melkuier, thanks for the PR :)
Interesting device :D I trust you have tested the code and verified that everything work, including flows, statistics etc?

I'll try to have this added with the next release but since I am ready to deploy it this might have to wait for next update.

I have added the extra code for the SmartPlug to the next release of the app already so that one will soon be supported.

**Comment by melkuier** [comment]
Hi Johan,

Thnx for creating the app as is is already. And All the work u already have done on it. (And still do)
The flows are working, and the energy monitoring in insights also seem to work.
We only struggled with the image SVG. So we ported a picture to an SVG. All your other appliances have different graphic images but I don't have graphic inspiration to make something like that on this device. I don't know if this is a problem.
Flows seem to work fine,  by statistics u mean insights? As far as I can see it also does the job.

We created a PR, but I have this version running local, so take your time. As I see there are a lot of requests for devices open, it seems more like a full time job.

As I already said, thnx for your app.
I'll send u a beer for the new year.!
Greetings
Tim.


Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

________________________________
Van: Johan Bendz ***@***.***>
Verstuurd: donderdag 30 december 2021 00:46
Aan: JohanBendz/com.tuya.zigbee
Cc: melkuier; Mention
Onderwerp: Re: [JohanBendz/com.tuya.zigbee] Added 4 channel relay board and smart metering plug (PR #137)


Hi @melkuier<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmelkuier&data=04%7C01%7C%7C951527011bfb45825fb808d9cb256a59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764183826898230%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3uQt9b8vHr1isYhKwzwO2wQrSTaVGNu4HrjC6vLndGE%3D&reserved=0>, thanks for the PR :)
Interesting device :D I trust you have tested the code and verified that everything work, including flows, statistics etc?

I'll try to have this added with the next release but since I am ready to deploy it this might have to wait for next update.

I have added the extra code for the SmartPlug to the next release of the app already so that one will soon be supported.

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJohanBendz%2Fcom.tuya.zigbee%2Fpull%2F137%23issuecomment-1002815629&data=04%7C01%7C%7C951527011bfb45825fb808d9cb256a59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764183826908185%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9CJME2qrprqiyjPDwBHAteOvV2Rm4egViqgyHml5%2By0%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ55VOWB3224I7CBU2VVH6LUTOMUZANCNFSM5K4PU7BQ&data=04%7C01%7C%7C951527011bfb45825fb808d9cb256a59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764183826908185%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=f46Az0XzreieI5eHQJ6zKDwX4WEiId2VxW1%2FnDbfdbk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C951527011bfb45825fb808d9cb256a59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764183826918135%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FK0uRVXeTu4XwTPM3JenoD9AXEg3%2FVCNJKvXd3sbDWE%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C951527011bfb45825fb808d9cb256a59%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764183826918135%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8CIjR9%2F1oBmNH7%2FvNAZvYprDME8ISfXK3xyTFntJt9A%3D&reserved=0>.

**Comment by tvandergeer** [comment]
See attached an icon I've created for this device: [icon.svg.zip](https://github.com/JohanBendz/com.tuya.zigbee/files/7792561/icon.svg.zip)

**Comment by JohanBendz** [comment]
Nice @tvandergeer
That icon is way better! :)

**Comment by JohanBendz** [comment]
Hi @melkuier and @tvandergeer, I have now added your code and images to the app.

I made some minor adjustments to the svg to have it resize correctly and look better (thicker lines) in small screens.
In the driver I changed the class from light to socket, this enables users to select what they have connected. Something many request for other units.
I also added platform (local for now) support to the driver as we will need this in place for future Bridge support.

All else looks great! :)

Closing PR. Code added manually. Credit given in readme file.

**Comment by melkuier** [comment]
Thnx! Great work!

I have still one question. I use it for window coverings, and tried to get the window covering interface, but it didn't work out. Any hint how to get this? Or isn't it that simple?


Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by JohanBendz** [comment]
The window covering capability is totally different from the on/off capability you use in this device. If you want this to work you will have to code a command parser that translates between the capabilities or work direktly with the Zigbee stack instead of working with Athom ready capabilities.

**Comment by melkuier** [comment]
Aha. Thnx
I'm already happy it works now! Thnx

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Pull request closed without merging**
