### PR TITLE
Added support din rail and curtain module 2nd generation

### PR DESCRIPTION
**Pull request by ayhamdabbas**
This pull request contains added support for 3 new devices:

DIN-rail relay with metering
Manufacturer: _TZ3000_qeuvnohg
ModelID: TS011F
MPN: TO-Q-SY1-JZT

DIN-rail relay with metering
Manufacturer: _TZ3000_cayepv1a
ModelID: TS011F
Commercial Brand: Tongou
MPN: TO-Q-SY2-JZT

DIY Curtain Module 2nd generation
Manufacturer: _TZ3000_e3vhyirx
ModelID: TS130F
Commercial Brand: LoraTap

### CODE REVIEW

**Comment by JohanBendz** [comment]
Hi @ayhamdabbas and thanks for the new PR.
A few comments:
1. I notice the icon (svg file) for the DIN module is wrong (it shows a plug), are you able to add a correct icon?
2. It looks like the only thing that differs between the "DIY Curtain Module 2nd generation" and the current curtain module already in the app is the missing device ID "_TZ3000_e3vhyirx". If this is correct I will just add the ID to the current driver, no need for a separate driver. If anything else differs, please advice.

// Johan

**Comment by ayhamdabbas** [comment]
Hi @JohanBendz 
Thank you for taking the time to review the pull request .
for the "DIY Curtain Module 2nd generation" we have created new driver to incorporate the windowcovering _set capability, which was added in the last commit. Additionally, there is a possibility of including the windowcoverings_tilt_set functionality in this driver. However, it remains uncertain whether all curtain modules support these capabilities.
//Ayham

**Comment by MihaiINW** [comment]
@JohanBendz 1. Could you please review our addition of the windowcovering_set capability. After that, let us know if we should leave it as a new driver or maybe move the changes to the existing curtain module driver.
2. We are not entirely sure how to add the proper icon for the smart plug DIN rail device, we have the correct small and large png files but we are not sure how to correctly make the icon.svg. Could you give us some advice on that?

**Comment by MihaiINW** [comment]
@JohanBendz We have corrected the icon issue for the DIN rail in the meantime.
Could you please have a look at the last two commits and let us know if you still think that we should put the changes in the existing curtain module driver or keep them in a separate driver (curtain_module_2nd_generation)?

**Comment by Boechie** [comment]
Hi @JohanBendz . Could you tell us if there are still any issues with this PR? We would really like to have it merged. ;-) Thx, the [Internetwerk](https://github.com/Internetwerk-Nederland-BV) team (including @ayhamdabbas , @MihaiINW, @theron8, @manarINW and @LuukINW)

**Comment by JohanBendz** [comment]
Hi @Boechie, sorry for the late feedback on this one. The Curtain Module is already supported by the app but I had missed this also contains the DIN module. Will now accept the PR and then delete your version of the Curtain Module. I notice someone already asked to have _TZ3000_cayepv1a added to the switch_2_gang_metering driver, if this is wrong and it should be in the same driver as _TZ3000_zmy4lslw I will change that. Please let me know.

**Comment by Boechie** [comment]
Hi @JohanBendz 

`I notice someone already asked to have _TZ3000_cayepv1a added to the switch_2_gang_metering driver`

This device is indeed NOT a 2 gang metering switch. It is 1 gang and also it is a plug, not a switch. In this PR we introduced a new driver smartplug_dinrail for that, but more of our changes are coming. Over the past few months our team has been working on major improvements for all kinds of plugs/switches/relays/meters. This is still not finished, but it will improve maintainability and extendability enormously. I will get in touch with you privately to see if you are willing to discuss our design ideas.

For the curtain module indeed, someone added it in the mean time. It will need further improvement which we are also working on now.

Thanks for accepting this PR for now. On the other hand it might be a better idea to not accept it (yet) as more improvements on these devices is coming up. Are you open to get in touch to discuss our further ideas?

**Pull request merged**
