### PR TITLE
Sdk3

### PR DESCRIPTION
**Pull request by rdl987**
Some new devices added.

### CODE REVIEW

**Comment by rdl987** [comment]
duration feature added to smart irrigator

**Comment by JohanBendz** [comment]
Thanks @rdl987. I'll have a look at it asap. 👍

**Comment by rdl987** [comment]
duration bug fixed

**Comment by JohanBendz** [comment]
Hi Rafael, sorry for having this on hold for so long. Some features have been implemented since before and rest is going into next update of the app. Thanks for the help and please do not let my slow actions stop you from contributing :)

**Pull request closed without merging**
