### PR TITLE
Added new devices _TZ3000_upgcbody / TS0207 _TZ3000_mugyhz0q / TS0207 _TZE200_jthf7vb6 / TS0601    

### LINKED ISSUE #568: Device Request - Flood Sensor - _TZ3000_upgcbody / TS0207
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name:  Water Sensor Leak Detector Flood Water
Device Model: 898WZ
Device Description: Flood Sensor
Link to device image: https://www.aliexpress.com/item/1005005066497327.html?spm=a2g0o.order_list.order_list_main.54.33361802HNX8Ep#nav-specification

Device Interview:
ID du fabricant : _TZ3000_upgcbody
ID du produit : TS0207
Recevoir lorsque inactif
⨯
Type d'appareil
enddevice
ID de l'appareil : a4:c1:38:e5:93:3e:8f:cb
Version du micrologiciel
Identifiants de groupe

Additional Comments:
Similar to _TZ3000_4uvovz4r / TS0207
When I try to interview the device I always get this answer : 
Interview failed (error: Failed to interview device (error: Timeout (25000ms): get node capabilities))
Are the info I put above enough to add this device? Otherwise can you help me get the device info trough the way explained below?

How to interview a device:
- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!

### LINKED ISSUE #587: Device Request - _TZ3000_upgcbody	TS0207 - Tuya / [n.a.]
Prerequisites:
- Before requesting a device addition, please ensure there is not already a request for the device among the open issues.
- Make sure your Homey is upgraded to firmware v5 or higher.
- You need a physical example of the device

Device Name: Water Leak detector
Device Model: TZ3000_upgcbody
Device Description: Water leak detection
Link to device image: https://nl.aliexpress.com/item/1005005220809595.html?spm=a2g0o.order_list.order_list_main.10.2bb379d2cQoUuB&gatewayAdapt=glo2nld

Device Interview:

  "ids": {
    "modelId": "TS0207",
    "manufacturerName": "_TZ3000_upgcbody"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          1,
          3,
          1280,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "identify": {
            "attributes": []
          },
          "iasZone": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zoneState",
                "value": "notEnrolled",
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "zoneType",
                "value": "waterSensor",
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "zoneStatus",
                "value": {
                  "type": "Buffer",
                  "data": [
                    0,
                    0
                  ]
                },
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 16,
                "name": "iasCIEAddress",
                "value": "00:12:4b:00:25:56:50:d5",
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 17,
                "name": "zoneId",
                "value": 6,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 65
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3000_upgcbody"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0207"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 2
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 6
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 8
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 9
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          },
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      }
    }
  }

Additional Comments:
[Provide any other relevant information or requests related to the device. Link to where you bought the device can be of help]

How to interview a device:
- Add the device as a generic Zigbee device in Homey
- Navigate to https://developer.athom.com/tools/zigbee.
- Interview the device, the button for this is to the right of the device in the list of Zigbee units.
- Click the copy button/icon to capture the device information.
- Paste the copied information above.

Note: To be able to add more devices to the Tuya Zigbee app, we rely on community members like you to provide interviews of the devices you want added. Thank you for your contribution!
image

### LINKED ISSUE #594: Device Request - Water Leakage Sensor with Alarm Siren - _TZ3000_mugyhz0q / TS0207
Device Name: ONENUO Water Leakage Sensor with Alarm Siren
Device Model: _TZ3000_mugyhz0q
Device Description: Water Detector Leakage Sensor with 80DB Alarm siren
Link to device image: https://ae01.alicdn.com/kf/S84f91d7629f34224a61c2a6d651d5bf8Q/ONENUO-Tuya-Zigbee-Water-Detector-Leakage-Sensor-Alarm-Leak-Detector-80DB-Sound-Smart-Life-APP-Flood.jpg_.webp

Device Interview:
`
  "ids": {
    "modelId": "TS0207",
    "manufacturerName": "_TZ3000_mugyhz0q"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:43:a1:01:dd:2e",
    "networkAddress": 11257,
    "modelId": "TS0207",
    "manufacturerName": "_TZ3000_mugyhz0q",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 11257,
        "_reserved": 20,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          1,
          3,
          1280,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          },
          "identify": {},
          "iasZone": {},
          "basic": {}
        },
        "bindings": {
          "ota": {},
          "time": {}
        }
      }
    }
  }`

Additional Comments:
Bought at aliexpress. https://www.aliexpress.com/item/1005005942082875.html
Same as _TZ3000_upgcbody but with alarm siren

### PR DESCRIPTION
**Pull request by obetsak**
Added new device ids and updated readme
Water detector
_TZ3000_upgcbody / TS0207 
_TZ3000_mugyhz0q / TS0207 

 Closes #594, Closes  #587, Closes #568

### CODE REVIEW

**Comment by obetsak** [comment]
Tested this change on my homey and the water detector devices worked but not sure why this device type is both a water alarm and a contact alarm since it uses the same sensor to trigger both. 

image

The Water leak sensor tuya did not work. The water alarm isn't triggered in homey.
Just managed to figure out how to build and deploy the app so now time to find out how to debug

**Comment by obetsak** [comment]
Not sure if the sensor code is wrong or this device is not compatible with the other sensor.
From my testing water alarm for _TZE200_jthf7vb6 / TS0601 is reported as dp = 1 and data = 0 not dp = 101 and data = 1

**Comment by obetsak** [comment]
removed _TZE200_jthf7vb6 since not 100% working

**Comment by fransjvos** [comment]
Hi All,
Good to see extra sensors that will be available. I have some of them. But maybe I miss something. The app does not seem to be updated. I only see Tuya Zigbee v0.2.18 Experimental in my HP2023. What needs to be done to get the app updated in my system? Am I doing something wrong or do I need to be more patient? Please forgive my ignorance.
Best regards,
Frans

**Comment by obetsak** [comment]
> Hi All, Good to see extra sensors that will be available. I have some of them. But maybe I miss something. The app does not seem to be updated. I only see Tuya Zigbee v0.2.18 Experimental in my HP2023. What needs to be done to get the app updated in my system? Am I doing something wrong or do I need to be more patient? Please forgive my ignorance. Best regards, Frans

The repo owner need to merge this PR and create a new testversion  or you need to download the code and deploy it our self to your homey.

**Comment by fransjvos** [comment]
Thanks for your quick reply :-) 
I hope for the update, I wouldn't know where to start deploying in my own Homey. Don't want to break anything...

**Comment by JohanBendz** [comment]
Thanks for the extra check with _TZE200_jthf7vb6, I notice this quite often.. devices looking the same but reporting using different data in the datapoint :/

Added the new ID's to next release. Please create a new ticket for _TZE200_jthf7vb6, if this is not already done :)

**Pull request closed without merging**
