### PR TITLE
New device Ty0201  _tz3000_bjawzodf

### PR DESCRIPTION
**Pull request by obetsak**
* Temperature and humidity reporting is working
* Battery reporting not working or at least nothing reported yet
* Not possible to configureAttributeReporting for powerConfiguration 
similar to lcdtemphumidsensor but without the back leg.
Was not possible to pair device unless i removed configureAttributeReporting from lcdtemphumidsensor 
response on configureAttributeReporting is "INVALID_DATA_TYPE"

`2023-12-19T20:48:34.735Z zigbee-clusters:cluster ep: 1, cl: powerConfiguration (1) configured reporting [
  ConfigureReportingResponse {
    status: 'INVALID_DATA_TYPE',
    direction: 'reported',
    attributeId: 33
  }
]
2023-12-19T20:48:34.738Z zigbee-clusters:cluster ep: 1, cl: powerConfiguration (1) configure reporting [
  {
    direction: 'reported',
    attributeId: 33,
    attributeDataType: 32,
    minInterval: 65535,
    maxInterval: 0,
    minChange: 0
  }
]
2023-12-19T20:48:34.739Z zigbee-clusters:cluster ep: 1, cl: powerConfiguration (1) send frame ZCLStandardHeader {
  frameControl: [],
  data: powerConfiguration.configureReporting { reports: [ [Object] ] },
  cmdId: 6,
  trxSequenceNumber: 3
}
2023-12-19T20:48:34.862Z zigbee-clusters:endpoint ep: 1, cl: undefined (57346), error while handling frame cluster_unavailable {
  meta: { dstEndpoint: 1 },
  frame: ZCLStandardHeader {
    frameControl: Bitmap [ directionToClient, disableDefaultResponse ],
    trxSequenceNumber: 23,
    cmdId: 10,
    data: <Buffer 0b e0 30 01>
  }
}
2023-12-19T20:48:34.902Z zigbee-clusters:cluster ep: 1, cl: powerConfiguration (1) received frame configureReporting.response powerConfiguration.configureReporting.response {
  reports: [
    ConfigureReportingResponse {
      status: 'INVALID_DATA_TYPE',
      direction: 'reported',
      attributeId: 33
    }
  ]
}
2023-12-19T20:48:34.902Z zigbee-clusters:cluster ep: 1, cl: powerConfiguration (1) configured reporting [
  ConfigureReportingResponse {
    status: 'INVALID_DATA_TYPE',
    direction: 'reported',
    attributeId: 33
  }
]
2023-12-19T20:48:34.903Z [err] [ManagerDrivers] [Driver:lcdtemphumidsensor] [Device:e52365ec-4312-4687-97de-9271f7d13a81] Error: configuring attribute reporting (endpoint: 1, cluster: powerConfiguration) {
  batteryPercentageRemaining: { minInterval: 65535, maxInterval: 0, minChange: 0 }
} Error: INVALID_DATA_TYPE
    at PowerConfigurationCluster.configureReporting (/app/node_modules/zigbee-clusters/lib/Cluster.js:516:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async lcdtemphumidsensor.onNodeInit (/app/drivers/lcdtemphumidsensor/device.js:14:4)
    at async /app/node_modules/homey-zigbeedriver/lib/ZigBeeDevice.js:957:11
2023-12-19T20:48:34.904Z [err] [ManagerDrivers] [Driver:lcdtemphumidsensor] [Device:e52365ec-4312-4687-97de-9271f7d13a81] Error: 'onNodeInit()' failed, reason: Error: INVALID_DATA_TYPE
    at PowerConfigurationCluster.configureReporting (/app/node_modules/zigbee-clusters/lib/Cluster.js:516:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async lcdtemphumidsensor.onNodeInit (/app/drivers/lcdtemphumidsensor/device.js:14:4)
    at async /app/node_modules/homey-zigbeedriver/lib/ZigBeeDevice.js:957:11
2023-12-19T20:48:34.905Z [err] [ManagerDrivers] [Driver:lcdtemphumidsensor] [Device:e52365ec-4312-4687-97de-9271f7d13a81] Error: could not initialize node Error: INVALID_DATA_TYPE
    at PowerConfigurationCluster.configureReporting (/app/node_modules/zigbee-clusters/lib/Cluster.js:516:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async lcdtemphumidsensor.onNodeInit (/app/drivers/lcdtemphumidsensor/device.js:14:4)
    at async /app/node_modules/homey-zigbeedriver/lib/ZigBeeDevice.js:957:11`

### CODE REVIEW

**Comment by gabrielczubak** [comment]
This is now quite a frequently sold device (tz3000_bjawzodf). It would be good to see it in this app. The code works for me (but doesn't really report the battery).

obraz

**Comment by obetsak** [comment]
The battery is the reason i closed the pull request but perhaps not the most important part of the device.
but om not really sure if this device then should be bundled with the other that report the  temp and humidity in the same way or if it should be considered a separate device. There isnt really a clear direction (that i can see) in the code or any discussions the i have seen how to handle this.

**Comment by obetsak** [comment]
> This is now quite a frequently sold device (tz3000_bjawzodf). It would be good to see it in this app. The code works for me (but doesn't really report the battery).
> 
> obraz

The battery is the reason i closed the pull request but perhaps not the most important part of the device.
but I am not really sure if this device then should be bundled with the other that report the temp and humidity in the same way or if it should be considered a separate device. There isnt really a clear direction (that i can see) in the code or any discussions the i have seen how to handle this.

**Comment by JohanBendz** [comment]
Hi @obetsak, Open it again and I will merge it. We can have a look at the battery part later. Sadly battery issues are quite common on Tuya devices.

**Pull request closed without merging**
