### PR TITLE
Add handheld 4 button remote

### PR DESCRIPTION
**Pull request by jepke**
https://github.com/athombv/homey-vectors-public/issues/229 icon.svg to be added

large

### CODE REVIEW

**Comment by JohanBendz** [comment]
Hi @jepke, nice PR. Can you please have a look at the titleFormatted part, it's currently not in line with Athoms expectations. 

```
Formatted titles
Flow cards may contain arguments. To integrate an argument into the title of the Flow card the titleFormated property must be used. Make sure that the title is still straightforward and clear with the arguments incorporated.
  "title": { "en": "Run a script" },
  "titleFormatted": { "en": "Run [[Script]]" }
Example: A remote or wall switch can have multiple buttons, with several actions to trigger them. For example pressed once, twice or a long press. Instead of creating several Flow cards for all these triggers, one flow card can be created containing several arguments. 
  "title": { "en": "Button was pressed" },
  "titleFormatted": { "en": "[[buttontype]] button was pressed [[scene]]" }
```

**Comment by jepke** [comment]
https://github.com/JohanBendz/com.tuya.zigbee/issues/365 will solve this issue

**Comment by jepke** [comment]
> Hi @jepke, nice PR. Can you please have a look at the titleFormatted part, it's currently not in line with Athoms expectations.
> 
> ```
> Formatted titles
> Flow cards may contain arguments. To integrate an argument into the title of the Flow card the titleFormated property must be used. Make sure that the title is still straightforward and clear with the arguments incorporated.
>   "title": { "en": "Run a script" },
>   "titleFormatted": { "en": "Run [[Script]]" }
> Example: A remote or wall switch can have multiple buttons, with several actions to trigger them. For example pressed once, twice or a long press. Instead of creating several Flow cards for all these triggers, one flow card can be created containing several arguments. 
>   "title": { "en": "Button was pressed" },
>   "titleFormatted": { "en": "[[buttontype]] button was pressed [[scene]]" }
> ```

good one i went with copying the wall_remote_4_gang_3 as it kinda works the same

**Comment by jepke** [comment]
wait isnt this what homey is asking for? Only 1 flow card with all the options
image

**Comment by jepke** [comment]
@JohanBendz think i understand this is what homey means by that?
image

Just have to figure out what to change in device.js as my remote goes haywire now lol

**Comment by JohanBendz** [comment]
@jepke LOL, yeah.. rewriting the flow cards can be a pain 😂 Give me a heads up when you have it working.

**Comment by jepke** [comment]
@JohanBendz 
Been using it in its current PR state for a few days now and its solid. Only nasty thing what those remotes do is send zigbee command twice. So the drawback is single tap cant be used as double action/toggle but its a device software flaw which im not surprised by with tuya.
My use case:
```
Single tap - turn on light
Double tap - turn off light
Long Press - Start a flow for a scene 
```
All that works flawless

Now just wait for Athom to supply a neat icon.svg

**Comment by JohanBendz** [comment]
@jepke Ivo/Athom delivers 😄 https://github.com/athombv/homey-vectors-public/blob/d811be7063f45d011005e344fe39fa237c503d45/com.tuya.zigbee/drivers/handheld_remote/assets/icon.svg

Please remove the app.json file from the PR too.

**Comment by jepke** [comment]
@JohanBendz 

Ill update the icon and remove app.json, just out of curiosity and lack of in depth understanding of the homey SDK thusfar from my end. Does app.json automatically get generate upon install with `homey app install` ?
If thats the case wouldnt it be better to add app.json to the gitignore file? this would avoid conflicts. I have those locally too constantly.

**Comment by jepke** [comment]
@JohanBendz should be all good now. Been reading docs up on the complete app manifest aka app.json not to be confused with the one inside the .homeycompose folder.

It's fully generated hence why im likely always fighting that file cross git branches locally. Correct me if im wrong but i dont think it would hurt to add it to the .gitignore. Only downside when you likely run a publish it gets generated making git think it needs a commit. Kinda feels stupid the Homey SDK works this way. It would make more sense if this file got generated upon regular install on the device locally, docs dont say anything about that. But if it does it should belong in .gitignore to avoid conflicts when multiple people are collaborating on the git project.

**Comment by JohanBendz** [comment]
Hi again @jepke, thanks for the updates. Merging. 😎
Yeah, I'v added it to gitignore and next update will have it.

**Pull request merged**
