### PR TITLE
switch_2_gang Update driver.settings.compose.json

### PR DESCRIPTION
**Pull request by TzK069**
@JohanBendz , can you assist?

### CODE REVIEW

**Comment by JohanBendz** [comment]
Hi @TzK069, you want to add Indicator setting to this device? It will require code in the device.js file too.
If you are sure the device supports it I can add the code for you to test and report, OK?

**Comment by TzK069** [comment]
Hey @JohanBendz , so happy to hear from you.

Yeah you can code it and i'll check it, the one gang already has this seeting activated, just need to the 2 gang version.

10x

**Comment by JohanBendz** [comment]
Hi again @TzK069, OK.. so you mean the "wall switch 1 gang" and "wall switch 2 gang".
In this PR you mention "switch 2 gang", this is an other device. ;)

So.. I'll add code to the "wall switch 2 gang" unit :)

**Comment by TzK069** [comment]
Ok, probably i wasan't clear.

I have one gang and two gang switches, from Moess... the 1 gang switch is working with the "indicator mode" LED on whwn gang is off and the other way, now I'm interested to do the same thing but for the 2gang thing

**Comment by JohanBendz** [comment]
OK Gotcha.
Just to check.. is there one light indicator for the device or is there one light indicator per button?

**Comment by TzK069** [comment]
one light indicator per button

**Comment by TzK069** [comment]
@JohanBendz any updates? let me know when I can test it so I can return with a feedback.

**Comment by JohanBendz** [comment]
@TzK069 
Upcoming update to the test version will have this implemented for all four models.

Please test and report back :)

**Comment by TzK069** [comment]
Hey @JohanBendz , saw that You updated the drivers, but for the wall_switch_2_gang, the model that I'm using is in the "switch_2_gang"

Model = _TZ3000_18ejxno0

Type = TS0012

It will not work, only if you add the model and type to the code.

**Comment by JohanBendz** [comment]
@TzK069, OK. So I should move _TZ3000_18ejxno0 from switch_2_gang to wall_switch_2_gang?

**Comment by TzK069** [comment]
Yeah, if the wall_switch_2_gang is the latest one that you update, from the 4 devices that you recently updated, then yes, you need to move from switch_2_gang -> wall_switch_2_gang

**Comment by TzK069** [comment]
and also 
model = _TZ3000_hhiodade
product id = TS0011

to be added as model to the wall_switch_1_gang

**Comment by JohanBendz** [comment]
@TzK069 OK, new version out now with this change and _TZ3000_hhiodade is added. Let me know if this works.

**Comment by TzK069** [comment]
Hey JohanBendz, 90% is working.
The 10 % is the fact that I can't select the second switch what is it plugged in.
Please see the picture attached 

Alex Ticuleanu0740.656.353 

    On Saturday, September 21, 2024 at 12:21:30 AM GMT+3, Johan Bendz ***@***.***> wrote:  
 
 


@TzK069 OK, new version out now with this change and _TZ3000_hhiodade is added. Let me know if this works.

**Comment by TzK069** [comment]
Hey JohanBendz, 90% is working.
The 10 % is the fact that I can't select the second switch what is it plugged in.
Please see the picture attached

**Comment by JohanBendz** [comment]
@TzK069 My bad, will fix.

**Pull request closed without merging**
